# TCL File Generated by Component Editor 22.1
# Tue Nov 07 11:16:13 CET 2023
# DO NOT MODIFY


# 
# avs_to_hram_converter "avs_to_hram_converter" v1.0
# Andrea Bononi 2023.11.07.11:16:13
# avalon memory-mapped slave to hyperRAM converter
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avs_to_hram_converter
# 
set_module_property DESCRIPTION "avalon memory-mapped slave to hyperRAM converter"
set_module_property NAME avs_to_hram_converter
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Andrea Bononi"
set_module_property DISPLAY_NAME avs_to_hram_converter
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point avs
# 
add_interface avs avalon end
set_interface_property avs addressUnits WORDS
set_interface_property avs associatedClock clk
set_interface_property avs associatedReset reset_n
set_interface_property avs bitsPerSymbol 8
set_interface_property avs bridgedAddressOffset 0
set_interface_property avs burstOnBurstBoundariesOnly false
set_interface_property avs burstcountUnits WORDS
set_interface_property avs explicitAddressSpan 0
set_interface_property avs holdTime 0
set_interface_property avs linewrapBursts false
set_interface_property avs maximumPendingReadTransactions 1
set_interface_property avs maximumPendingWriteTransactions 0
set_interface_property avs readLatency 0
set_interface_property avs readWaitTime 1
set_interface_property avs setupTime 0
set_interface_property avs timingUnits Cycles
set_interface_property avs writeWaitTime 0
set_interface_property avs ENABLED true
set_interface_property avs EXPORT_OF ""
set_interface_property avs PORT_NAME_MAP ""
set_interface_property avs CMSIS_SVD_VARIABLES ""
set_interface_property avs SVD_ADDRESS_GROUP ""

add_interface_port avs avs_address address Input 32
add_interface_port avs avs_read read Input 1
add_interface_port avs avs_readdata readdata Output 16
add_interface_port avs avs_write write Input 1
add_interface_port avs avs_writedata writedata Input 16
add_interface_port avs avs_waitrequest waitrequest Output 1
add_interface_port avs avs_readdatavalid readdatavalid Output 1
add_interface_port avs avs_beginbursttransfer beginbursttransfer Input 1
add_interface_port avs avs_burstcount burstcount Input 1
set_interface_assignment avs embeddedsw.configuration.isFlash 0
set_interface_assignment avs embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Input 1


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clk
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n CMSIS_SVD_VARIABLES ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n reset_n reset Input 1


# 
# connection point hram_RESET_n
# 
add_interface hram_RESET_n reset start
set_interface_property hram_RESET_n associatedClock hram_CK
set_interface_property hram_RESET_n associatedDirectReset reset_n
set_interface_property hram_RESET_n associatedResetSinks reset_n
set_interface_property hram_RESET_n synchronousEdges DEASSERT
set_interface_property hram_RESET_n ENABLED true
set_interface_property hram_RESET_n EXPORT_OF ""
set_interface_property hram_RESET_n PORT_NAME_MAP ""
set_interface_property hram_RESET_n CMSIS_SVD_VARIABLES ""
set_interface_property hram_RESET_n SVD_ADDRESS_GROUP ""

add_interface_port hram_RESET_n hram_RESET_n reset Output 1


# 
# connection point hram_CK
# 
add_interface hram_CK clock start
set_interface_property hram_CK associatedDirectClock clk
set_interface_property hram_CK clockRate 0
set_interface_property hram_CK clockRateKnown false
set_interface_property hram_CK ENABLED true
set_interface_property hram_CK EXPORT_OF ""
set_interface_property hram_CK PORT_NAME_MAP ""
set_interface_property hram_CK CMSIS_SVD_VARIABLES ""
set_interface_property hram_CK SVD_ADDRESS_GROUP ""

add_interface_port hram_CK hram_CK clk Output 1


# 
# connection point hyperbus_master
# 
add_interface hyperbus_master conduit end
set_interface_property hyperbus_master associatedClock hram_CK
set_interface_property hyperbus_master associatedReset hram_RESET_n
set_interface_property hyperbus_master ENABLED true
set_interface_property hyperbus_master EXPORT_OF ""
set_interface_property hyperbus_master PORT_NAME_MAP ""
set_interface_property hyperbus_master CMSIS_SVD_VARIABLES ""
set_interface_property hyperbus_master SVD_ADDRESS_GROUP ""

add_interface_port hyperbus_master hram_DQ data_stream Bidir 8
add_interface_port hyperbus_master hram_RWDS data_strobe Bidir 1
add_interface_port hyperbus_master hram_CS_n chipselect Output 1

